import random

def flatten_list(nested_list):
    return [item for sublist in nested_list for item in sublist]

def classify_scene(categories, attributes):
    
    # Mappings for categories
    category_music_map = {
        "airfield": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "airplane_cabin": ("Mellow", ["Piano", "Synthesizer"], "Relaxed"),
        "airport_terminal": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "alcove": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "alley": ("Catchy", ["Guitar", "Drums"], "Excited"),
        "amphitheater": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "amusement_arcade": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "apartment_building/outdoor": ("Soothing", ["Piano", "Guitar"], "Relaxed"),
        "aqueduct": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "arcade": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "arch": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "archaelogical_excavation": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "archive": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "arena/hockey": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "arena/performance": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "arena/rodeo": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "army_base": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "art_school": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "art_studio": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "artists_loft": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "assembly_line": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "athletic_field/outdoor": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "atrium/public": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "attic": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "auditorium": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "auto_factory": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "auto_showroom": ("Catchy", ["Guitar", "Drums"], "Excited"),
        "badlands": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "bakery/shop": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "balcony/exterior": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "balcony/interior": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "ball_pit": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "ballroom": ("Romantic", ["Piano", "Violin"], "Nostalgic"),
        "bamboo_forest": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "bank_vault": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "banquet_hall": ("Romantic", ["Piano", "Violin"], "Nostalgic"),
        "bar": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "barn": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "barndoor": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "baseball_field": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "basement": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "basketball_court/indoor": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "bathroom": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "bazaar/indoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "bazaar/outdoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "beauty_salon": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "bedchamber": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "bedroom": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "beer_garden": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "beer_hall": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "berth": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "biology_laboratory": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "boardwalk": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "boat_deck": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "boathouse": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "bookstore": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "booth/indoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "botanical_garden": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "bow_window/indoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "bowling_alley": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "boxing_ring": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "bridge": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "building_facade": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "bullring": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "burial_chamber": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "bus_interior": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "bus_station/indoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "butchers_shop": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "butte": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "cabin/outdoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "cafeteria": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "campus": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "canal/natural": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "canal/urban": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "candy_store": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "canyon": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "car_interior": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "carrousel": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "castle": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "catacomb": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "cemetery": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "chalet": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "chemistry_lab": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "childs_room": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "church/indoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "church/outdoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "classroom": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "clean_room": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "cliff": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "closet": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "clothing_store": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "coast": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "cockpit": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "coffee_shop": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "computer_room": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "conference_center": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "conference_room": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "construction_site": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "corn_field": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "corral": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "corridor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "cottage": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "courthouse": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "courtyard": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "creek": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "crevasse": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "crosswalk": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "dam": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "delicatessen": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "department_store": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "desert/sand": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "desert/vegetation": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "desert_road": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "diner/outdoor": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "dining_hall": ("Romantic", ["Piano", "Violin"], "Nostalgic"),
        "dining_room": ("Romantic", ["Piano", "Violin"], "Nostalgic"),
        "discotheque": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "doorway/outdoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "dorm_room": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "downtown": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "dressing_room": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "driveway": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "drugstore": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "elevator/door": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "elevator_lobby": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "elevator_shaft": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "embassy": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "engine_room": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "entrance_hall": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "escalator/indoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "excavation": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "fabric_store": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "farm": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "fastfood_restaurant": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "field/cultivated": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "field/wild": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "field_road": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "fire_escape": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "fire_station": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "fishpond": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "flea_market/indoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "florist_shop/indoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "food_court": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "football_field": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "forest/broadleaf": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "forest_path": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "forest_road": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "formal_garden": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "fountain": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "galley": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "garage/indoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "garage/outdoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "gas_station": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "gazebo/exterior": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "general_store/indoor": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "general_store/outdoor": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "gift_shop": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "glacier": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "golf_course": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "greenhouse/indoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "greenhouse/outdoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "grotto": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "gymnasium/indoor": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "hangar/indoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "hangar/outdoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "harbor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "hardware_store": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "hayfield": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "heliport": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "highway": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "home_office": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "home_theater": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "hospital": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "hospital_room": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "hot_spring": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "hotel/outdoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "hotel_room": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "house": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "hunting_lodge/outdoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "ice_cream_parlor": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "ice_floe": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "ice_shelf": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "ice_skating_rink/indoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "ice_skating_rink/outdoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "iceberg": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "igloo": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "industrial_area": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "inn/outdoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "islet": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "jacuzzi/indoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "jail_cell": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "japanese_garden": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "jewelry_shop": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "junkyard": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "kasbah": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "kennel/outdoor": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "kindergarden_classroom": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "kitchen": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "lagoon": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "lake/natural": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "landfill": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "landing_deck": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "laundromat": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "lawn": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "lecture_room": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "legislative_chamber": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "library/indoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "library/outdoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "lighthouse": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "living_room": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "loading_dock": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "lobby": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "lock_chamber": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "locker_room": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "mansion": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "manufactured_home": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "market/indoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "market/outdoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "marsh": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "martial_arts_gym": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "mausoleum": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "medina": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "mezzanine": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "moat/water": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "mosque/outdoor": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "motel": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "mountain": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "mountain_path": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "mountain_snowy": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "movie_theater/indoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "museum/indoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "museum/outdoor": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "music_studio": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "natural_history_museum": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "nursery": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "nursing_home": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "oast_house": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "ocean": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "office": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "office_building": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "office_cubicles": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "oilrig": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "operating_room": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "orchard": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "orchestra_pit": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "pagoda": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "palace": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "pantry": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "park": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "parking_garage/indoor": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "parking_garage/outdoor": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "parking_lot": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "pasture": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "patio": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "pavilion": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "pet_shop": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "pharmacy": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "phone_booth": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "physics_laboratory": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "picnic_area": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "pier": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "pizzeria": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "playground": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "playroom": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "plaza": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "pond": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "porch": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "promenade": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "pub/indoor": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "racecourse": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "raceway": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "raft": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "railroad_track": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "rainforest": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "reception": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "recreation_room": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "repair_shop": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "residential_neighborhood": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "restaurant": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "restaurant_kitchen": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "restaurant_patio": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "rice_paddy": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "river": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "rock_arch": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "rope_bridge": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "ruin": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "runway": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "sandbox": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "sauna": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "schoolhouse": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "sea_cliff": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "seashore": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "server_room": ("Inspirational", ["Piano", "Drums"], "Motivated"),
        "shed": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "shoe_shop": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "shopfront": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "shopping_mall/indoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "shower": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "ski_resort": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "ski_slope": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "sky": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "skyscraper": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "slum": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "snowfield": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "soccer_field": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "stable": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "stadium/indoor": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "stadium/outdoor": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "stage/indoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "stage/outdoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "staircase": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "storage_room": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "street": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "subway_station/indoor": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "supermarket": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "swamp": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "swimming_pool/indoor": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "swimming_pool/outdoor": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "synagogue/indoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "synagogue/outdoor": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "television_room": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "temple/asia": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "throne_room": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "ticket_booth": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "topiary_garden": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "tower": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "toyshop": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "track/outdoor": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "train_interior": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "train_station/platform": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "tree_farm": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "tree_house": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "trench": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "underwater/ocean_deep": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "utility_room": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "valley": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "vegetable_garden": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "veranda": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "veterinarians_office": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "viaduct": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "village": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "vineyard": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "volcano": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "volleyball_court": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "waiting_room": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "water_park": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "water_tower": ("Epic", ["Synthesizer", "Drums"], "Motivated"),
        "waterfall": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "watering_hole": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "wave": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "wet_bar": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "wheat_field": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "wind_farm": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "windmill": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "yard": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "youth_hostel": ("Playful", ["Piano", "Trumpet"], "Happy")
    }

    # # Mappings for attributes
    attribute_music_map = {
        "boating": ("Soothing", ["Guitar", "Piano"], "Relaxed"),
        "driving": ("Energetic", ["Guitar", "Drums"], "Excited"),
        "biking": ("Energetic", ["Guitar", "Drums"], "Excited"),
        "camping": ("Soothing", ["Guitar", "Drums"], "Relaxed"),
        "reading": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "working": ("Inspirational", ["Piano", "Synthesizer"], "Motivated"),
        "socializing": ("Playful", ["Piano", "Trumpet"], "Happy"),
        "waiting_in_line": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "sports": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "shopping": ("Catchy", ["Synthesizer", "Drums"], "Excited"),
        "farming": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "constructing": ("Energetic", ["Drums", "Guitar"], "Excited"),
        "praying": ("Soothing", ["Piano", "Flute"], "Relaxed"),
        "swimming": ("Soothing", ["Guitar", "Piano"], "Relaxed"),
        "diving": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "picnic": ("Soothing", ["Guitar", "Flute"], "Relaxed"),
        "exercising": ("Energetic", ["Drums", "Bass Guitar"], "Excited"),
        "exploring": ("Soothing", ["Piano", "Guitar"], "Relaxed"),
        "movie_night": ("Mellow", ["Piano", "Violin"], "Relaxed"),
        "barbecue": ("Playful", ["Piano", "Guitar"], "Happy"),
        "road_trip": ("Energetic", ["Guitar", "Drums"], "Excited"),
        "celebration": ("Energetic", ["Synthesizer", "Drums"], "Excited"),
        "chill_out": ("Soothing", ["Guitar", "Piano"], "Relaxed"),
        "romantic_dinner": ("Romantic", ["Piano", "Violin"], "Nostalgic"),
        "relaxation": ("Soothing", ["Flute", "Piano"], "Relaxed"),
        "morning_routine": ("Soothing", ["Piano", "Flute"], "Relaxed")
    }

    # Default values
    default_music_type = "Soothing"
    default_instruments = ["Piano", "Drums"]
    default_impression = "Relaxed"

    top_categories = [item.split(" -> ")[1] for item in categories[:2]]  # Extract category names
    top_attributes = flatten_list(attributes)[:2]  # Flatten attributes and take top 2


    music_type = None
    instruments = []
    impression = None
    
    musicTypeList = []
    instrumentsList = []
    impressionList = []

    for cat in top_categories:
        if cat in category_music_map:
            music_type, instruments, impression = category_music_map[cat]
            musicTypeList.append(music_type)
            instrumentsList.append(instruments)
            impressionList.append(impression)
    
    if not music_type:
        for attr in top_attributes:
            if attr in attribute_music_map:
                
                attr_music_type, attr_instruments, attr_impression = attribute_music_map[attr]
                if not instruments:  # If instruments are not set, use attribute instruments
                    instruments = attr_instruments
                if not impression:  # If impression is not set, use attribute impression
                    impression = attr_impression
                if attr_music_type != default_music_type:  # Use attribute music type if different
                    music_type = attr_music_type
                else:
                    music_type = default_music_type
                break

    #if not music_type:
        #music_type = "Soothing"  # Default to soothing if no match is found
    #if not instruments:
        #instruments = ["Piano", "Drums"]  # Default instruments if no match is found
    #if not impression:
        #impression = "Relaxed"
        
    # Create the prompt
    prompt = f"Create a {musicTypeList[0].lower()} music piece featuring {', '.join(instrumentsList[1])} with {impressionList[0].lower()} feeling."
    #prompt = f"Create a {music_type.lower()} music piece featuring {', '.join(instruments)} with {impression.lower()} feeling."
    return prompt

def getPrompt(val):
    ambience = val[0]
    categories = val[1]
    attributes = val[2]

    ansPrompt = classify_scene(categories, attributes)

    return ansPrompt
    
    